# Generated by Django 4.2.5 on 2023-10-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='time_z',
            field=models.DateField(blank=True, null=True, verbose_name='Время создания'),
        ),
    ]
