# Generated by Django 4.2.5 on 2023-10-03 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0002_alter_zayavka_time_z'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='user_z',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
