# Generated by Django 4.2.5 on 2023-10-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0004_alter_zayavka_time_z'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=30, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='zayavka',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interior.category', verbose_name='Категория'),
        ),
    ]
