# Generated by Django 4.2.5 on 2023-10-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0005_category_zayavka_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='interior.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='zayavka',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
