# Generated by Django 3.2.21 on 2023-10-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0007_alter_zayavka_category_alter_zayavka_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='image_done',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Выполненый дизайн'),
        ),
    ]
