# Generated by Django 3.2.21 on 2023-10-04 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0008_auto_20231004_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interior.category', verbose_name='Категория'),
        ),
    ]
