# Generated by Django 4.2.5 on 2023-10-04 19:25

from django.db import migrations, models
import interior.models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0009_alter_zayavka_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='image',
            field=models.FileField(upload_to='', validators=[interior.models.file_size]),
        ),
    ]
